name: fake_icon
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.4
  font_awesome_flutter: ^10.3.0
  image_picker: ^0.8.6
  flutter_launcher_icons: ^0.11.0
  shared_preferences: ^2.0.15
  dotted_border: ^2.0.0+3
  flutter_native_splash: ^2.1.3+1

flutter_native_splash:
  color: '#FFFFFF'
  image: 'images/fake-icon-logo.png'
  fullscreen: true
  android_12:
    icon_background_color: '#add8e6'
    image: 'images/fake-icon-logo-L.png'

flutter_icons:
  image_path: "images/fakeIcon-icon.jpg"
  ios: true
  android: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/tutorial-background-change.gif
    - images/tutorial-icon-change.gif
    - images/tutorial-splash-demo.gif
  fonts:
    - family: Delicious_Handrawn
      fonts:
        - asset: assets/fonts/Delicious_Handrawn/DeliciousHandrawn-Regular.ttf
    - family: mogihaPen
      fonts:
        - asset: assets/fonts/mogihaPen_ver120/mogihaPen.ttf
    - family: Noto_Sans_JP
      fonts:
        - asset: assets/fonts/Noto_Sans_JP/static/NotoSansJP-Thin.ttf
          weight: 100
        - asset: assets/fonts/Noto_Sans_JP/static/NotoSansJP-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Noto_Sans_JP/static/NotoSansJP-Light.ttf
          weight: 300
        - asset: assets/fonts/Noto_Sans_JP/static/NotoSansJP-Regular.ttf
          weight: 400
        - asset: assets/fonts/Noto_Sans_JP/static/NotoSansJP-Medium.ttf
          weight: 500
        - asset: assets/fonts/Noto_Sans_JP/static/NotoSansJP-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Noto_Sans_JP/static/NotoSansJP-Bold.ttf
          weight: 700
        - asset: assets/fonts/Noto_Sans_JP/static/NotoSansJP-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Noto_Sans_JP/static/NotoSansJP-Black.ttf
          weight: 900

